---
- name: Install Java
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Validate Java installation
  shell: java -version
  register: java_version
  changed_when: false

- name: Create Tomcat group
  group:
    name: tomcat
    state: present

- name: Create Tomcat user
  user:
    name: tomcat
    group: tomcat
    shell: /bin/bash
    state: present

- name: Create Tomcat directory
  file:
    path: /opt/tomcat8
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: Download and unarchive Tomcat
  unarchive:
    src: "{{ download_url }}"
    dest: /opt/tomcat8
    remote_src: yes
    extra_opts:
      - --strip-components=1
    owner: tomcat
    group: tomcat

- name: Create Tomcat systemd service file
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'

- name: Reload systemd to pick up new Tomcat service file
  systemd:
    daemon_reload: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes

- name: Check Tomcat is running
  uri:
    url: http://localhost:8080
    status_code: 200
  register: result
  until: result.status == 200
  retries: 5
  delay: 10